### ISSUE TITLE
Compiled readthedocs document absent

### ISSUE THREAD

**Issue by Radiation-Transport** [Radiation-Transport/F4Enix#27]
The compiled readthedocs document has not been included in the Github repository.
Please add them at least in PDF.

**Comment by dodu94** [comment]
As discussed, this would be useless once the readthedocs hmtl version will be online

**Comment by Radiation-Transport** [comment]
Issued resolved with commit#[d9429d9429](https://github.com/Radiation-Transport/F4Enix/commit/41d942935550ce4cdaf92deec3b5d75cb6c12b9b)
