### ISSUE TITLE
extract_cells() method creates double null line before the tr cards

### ISSUE THREAD

**Issue by Radiation-Transport** [Radiation-Transport/F4Enix#42]
inp.extract_cells([9427075,9427076],'VV_PS1_FJ.i') 

extract_cells() method creates double null line before the tr cards generating a fatal error.

![image](https://github.com/Radiation-Transport/F4Enix/assets/48320561/ff5e6bd1-9283-4717-a2c6-d49b8d4728ee)

**Comment by dodu94** [comment]
Yes this happens if no materials are present, we are already working on it.

I'll close the issue since it is a duplicated of #32.
